- hosts: belgie
  vars: 
    gitrepo: https://github.com/BeauRoels/Infracloud
    destination: /home/ikwildood/Desktop/github/Infracloud/DeployFlask_15Testing
  tasks:
    - name: Install Git On Machine
      become: yes
      apt: 
        name: "{{ item }}"
        state: latest
      loop: ["git","ca-certificates","curl","gnupg","lsb-release","apt-transport-https","curl","software-properties-common"]

    - name: Clone The Repository
      git: 
        repo: "{{ gitrepo }}"
        dest: "{{ destination }}"
        clone: yes
        update: yes

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Git On Machine
      become: yes
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: ["docker-ce", "docker-ce-cli", "containerd.io"]
